name: Build and Release Signal Analyzer

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r build_requirements.txt
        pip install pillow  # For icon creation
        
    - name: Create version info
      run: |
        $version = "${{ github.event.inputs.version || github.ref_name }}"
        $version = $version -replace '^v', ''  # Remove 'v' prefix if present
        $date = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
        $versionInfo = @{
          version = $version
          build_date = $date
          description = "Signal Analyzer - Advanced Signal Processing Tool"
          company = "Signal Analysis Lab"
          product = "Signal Analyzer"
          commit_hash = "${{ github.sha }}"
        }
        $versionInfo | ConvertTo-Json | Out-File -FilePath "version_info.json" -Encoding UTF8
        
    - name: Build executable
      run: |
        python build.py
        
    - name: List build output
      run: |
        Get-ChildItem -Recurse dist/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # FIXED: Updated from v3 to v4
      with:
        name: signal-analyzer-windows
        path: dist/SignalAnalyzer_*.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
        name: Signal Analyzer ${{ github.event.inputs.version || github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/SignalAnalyzer_*.zip
        body: |
          ## Signal Analyzer Release
          
          ### What's New
          - Latest version of Signal Analyzer with improved performance
          - Bug fixes and stability improvements
          
          ### Download Instructions
          1. Download the `SignalAnalyzer_*.zip` file
          2. Extract the ZIP file to a folder on your computer
          3. Run `SignalAnalyzer.exe` from the extracted folder
          
          ### System Requirements
          - Windows 10 or later
          - No additional software installation required
          
          ### For Teachers
          This is the latest stable version for classroom use. All students can download and run this version directly.
          
          **Build Date:** ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}